{{- $root := . -}}
{{- with $root.Values.secretProviderClass }}
{{- if and .secrets .keyvaultName .tenantId }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "app.fullname" $root }}
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "app.fullname" $root }}   # <- K8s Secret name
      type: Opaque
      data:
{{- $secrets := .secrets -}}
{{- $keys := keys $secrets | sortAlpha -}}
{{- range $keys }}
        - key: {{ . }}
          objectName: {{ (index $secrets .).objectName }}
{{- end }}
  parameters:
    keyvaultName: {{ .keyvaultName | quote }}
    tenantId: {{ .tenantId | quote }}
    objects: |
      array:
{{- range $keys }}
        - |
          objectName: {{ (index $secrets .).objectName }}
          objectType: {{ default "secret" ((index $secrets .).objectType) }}
          objectVersion: {{ default "" ((index $secrets .).objectVersion) | quote }}
{{- end }}
{{- end }}
{{- end }}
