export const explosionDrawingData1 = {
  list: [
    {
      id: 1,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "37",
      sortId: null,
      partNumber: "1600100033",
      partNumberFormatted: "1 600 100 033",
      partName: "Cover Disc ",
      quantity: 1,
      price: 35.33,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "13",
      illustrationNumber: "1",
      posxmax: 835,
      posxmin: 816,
      posymax: 267,
      posymin: 254,
    },
    {
      id: 2,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "41",
      sortId: null,
      partNumber: "1600200029",
      partNumberFormatted: "1 600 200 029",
      partName: "Plain bearing ",
      quantity: 1,
      price: 40.74,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "14",
      illustrationNumber: "1",
      posxmax: 1084,
      posxmin: 1067,
      posymax: 312,
      posymin: 299,
    },
    {
      id: 3,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "27",
      sortId: null,
      partNumber: "1600206025",
      partNumberFormatted: "1 600 206 025",
      partName: "Rubber Ring ",
      quantity: 1,
      price: 28.97,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "12",
      illustrationNumber: "1",
      posxmax: 782,
      posxmin: 763,
      posymax: 237,
      posymin: 224,
    },
    {
      id: 4,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "26",
      sortId: null,
      partNumber: "1600502023",
      partNumberFormatted: "1 600 502 023",
      partName: "Intermediate Ring ",
      quantity: 1,
      price: 28.97,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "12",
      illustrationNumber: "1",
      posxmax: 480,
      posxmin: 461,
      posymax: 67,
      posymin: 54,
    },
    {
      id: 5,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "7",
      sortId: null,
      partNumber: "1601302017",
      partNumberFormatted: "1 601 302 017",
      partName: "Fastening Clamp ",
      quantity: 1,
      price: 12.68,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 553,
      posxmin: 543,
      posymax: 368,
      posymin: 355,
    },
    {
      id: 6,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "32",
      sortId: null,
      partNumber: "1603523111",
      partNumberFormatted: "1 603 523 111",
      partName: "Grinding Spindle M10, SW12",
      quantity: 1,
      price: 101.08,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "19",
      illustrationNumber: "1",
      posxmax: 1094,
      posxmin: 1076,
      posymax: 720,
      posymin: 707,
    },
    {
      id: 7,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "3",
      sortId: null,
      partNumber: "1604010BM9",
      partNumberFormatted: "1 604 010 BM9",
      partName: "Armature ",
      quantity: 1,
      price: 512.63,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "33",
      illustrationNumber: "1",
      posxmax: 609,
      posxmin: 600,
      posymax: 116,
      posymin: 103,
    },
    {
      id: 8,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "2",
      sortId: null,
      partNumber: "160422059E",
      partNumberFormatted: "1 604 220 59E",
      partName: "Field ",
      quantity: 1,
      price: 0,
      priceCurrencyISO: null,
      priceCurrencySymbol: null,
      priceGroup: null,
      illustrationNumber: "1",
      posxmax: 800,
      posxmin: 790,
      posymax: 578,
      posymin: 564,
    },
    {
      id: 9,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "17",
      sortId: null,
      partNumber: "1604652013",
      partNumberFormatted: "1 604 652 013",
      partName: "Spiral Spring ",
      quantity: 2,
      price: 21.72,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 448,
      posxmin: 430,
      posymax: 646,
      posymin: 633,
    },
    {
      id: 10,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "17",
      sortId: null,
      partNumber: "1604652013",
      partNumberFormatted: "1 604 652 013",
      partName: "Spiral Spring ",
      quantity: 2,
      price: 21.72,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 553,
      posxmin: 535,
      posymax: 291,
      posymin: 278,
    },
    {
      id: 11,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "805",
      sortId: null,
      partNumber: "1607000387",
      partNumberFormatted: "1 607 000 387",
      partName: "Power supply cord CN 2,65M 2 X 0,75MM H05 W-F",
      quantity: 1,
      price: 159.34,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "23",
      illustrationNumber: "1",
      posxmax: 243,
      posxmin: 216,
      posymax: 434,
      posymin: 420,
    },
    {
      id: 12,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "4",
      sortId: null,
      partNumber: "160720031V",
      partNumberFormatted: "1 607 200 31V",
      partName: "Switch ",
      quantity: 1,
      price: 89.57,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "22",
      illustrationNumber: "1",
      posxmax: 598,
      posxmin: 588,
      posymax: 356,
      posymin: 342,
    },
    {
      id: 13,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "50",
      sortId: null,
      partNumber: "1619P00105",
      partNumberFormatted: "1 619 P00 105",
      partName: "Torx Oval-Head Screw 4X20",
      quantity: 1,
      price: 24.8,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 179,
      posxmin: 160,
      posymax: 261,
      posymin: 248,
    },
    {
      id: 14,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "48",
      sortId: null,
      partNumber: "1619P00220",
      partNumberFormatted: "1 619 P00 220",
      partName: "Torx Oval-Head Screw 3X10",
      quantity: 2,
      price: 12.02,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 504,
      posxmin: 485,
      posymax: 267,
      posymin: 254,
    },
    {
      id: 15,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "48",
      sortId: null,
      partNumber: "1619P00220",
      partNumberFormatted: "1 619 P00 220",
      partName: "Torx Oval-Head Screw 3X10",
      quantity: 2,
      price: 12.02,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 557,
      posxmin: 538,
      posymax: 702,
      posymin: 688,
    },
    {
      id: 16,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "36",
      sortId: null,
      partNumber: "1619P00987",
      partNumberFormatted: "1 619 P00 987",
      partName: "Washer ",
      quantity: 1,
      price: 12.42,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 692,
      posxmin: 674,
      posymax: 183,
      posymin: 169,
    },
    {
      id: 17,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "55",
      sortId: null,
      partNumber: "1619P01066",
      partNumberFormatted: "1 619 P01 066",
      partName: "Torx Oval-Head Screw 4X25",
      quantity: 4,
      price: 12.02,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 1062,
      posxmin: 1043,
      posymax: 151,
      posymin: 137,
    },
    {
      id: 18,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "16",
      sortId: null,
      partNumber: "1619P01811",
      partNumberFormatted: "1 619 P01 811",
      partName: "Brush Holder ",
      quantity: 2,
      price: 37.88,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "14",
      illustrationNumber: "1",
      posxmax: 484,
      posxmin: 466,
      posymax: 343,
      posymin: 330,
    },
    {
      id: 19,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "16",
      sortId: null,
      partNumber: "1619P01811",
      partNumberFormatted: "1 619 P01 811",
      partName: "Brush Holder ",
      quantity: 2,
      price: 37.88,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "14",
      illustrationNumber: "1",
      posxmax: 571,
      posxmin: 553,
      posymax: 621,
      posymin: 608,
    },
    {
      id: 20,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "35",
      sortId: null,
      partNumber: "1619P02821",
      partNumberFormatted: "1 619 P02 821",
      partName: "Shim 0,1 MM",
      quantity: 1,
      price: 12.42,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 1094,
      posxmin: 1076,
      posymax: 440,
      posymin: 427,
    },
    {
      id: 21,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "35",
      sortId: null,
      partNumber: "1619P02822",
      partNumberFormatted: "1 619 P02 822",
      partName: "Shim 0,2 MM",
      quantity: 1,
      price: 14,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 1094,
      posxmin: 1076,
      posymax: 440,
      posymin: 427,
    },
    {
      id: 22,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "38",
      sortId: null,
      partNumber: "1619P02823",
      partNumberFormatted: "1 619 P02 823",
      partName: "Crown Gear ",
      quantity: 1,
      price: 136.28,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "21",
      illustrationNumber: "1",
      posxmax: 959,
      posxmin: 940,
      posymax: 376,
      posymin: 362,
    },
    {
      id: 23,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "39",
      sortId: null,
      partNumber: "1619P02825",
      partNumberFormatted: "1 619 P02 825",
      partName: "Bevel Gear ",
      quantity: 1,
      price: 67.31,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "17",
      illustrationNumber: "1",
      posxmax: 860,
      posxmin: 841,
      posymax: 357,
      posymin: 343,
    },
    {
      id: 24,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "28/1",
      sortId: null,
      partNumber: "1619P07440",
      partNumberFormatted: "1 619 P07 440",
      partName: "Ball Bearing ",
      quantity: 1,
      price: 82.32,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "19",
      illustrationNumber: "1",
      posxmax: 963,
      posxmin: 934,
      posymax: 521,
      posymin: 508,
    },
    {
      id: 25,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "828",
      sortId: null,
      partNumber: "1619P07451",
      partNumberFormatted: "1 619 P07 451",
      partName: "Bearing Flange ",
      quantity: 1,
      price: 222.14,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "27",
      illustrationNumber: "1",
      posxmax: 907,
      posxmin: 880,
      posymax: 567,
      posymin: 554,
    },
    {
      id: 26,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "13",
      sortId: null,
      partNumber: "1619P08829",
      partNumberFormatted: "1 619 P08 829",
      partName: "groove ball bearing ",
      quantity: 1,
      price: 93.14,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "19",
      illustrationNumber: "1",
      posxmax: 504,
      posxmin: 486,
      posymax: 83,
      posymin: 69,
    },
    {
      id: 27,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "80",
      sortId: null,
      partNumber: "1619P09390",
      partNumberFormatted: "1 619 P09 390",
      partName: "Cover Disc ",
      quantity: 1,
      price: 34.65,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "12",
      illustrationNumber: "1",
      posxmax: 953,
      posxmin: 934,
      posymax: 644,
      posymin: 631,
    },
    {
      id: 28,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "1",
      sortId: null,
      partNumber: "1619P10958",
      partNumberFormatted: "1 619 P10 958",
      partName: "Motor Housing ",
      quantity: 1,
      price: 84.8,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "17",
      illustrationNumber: "1",
      posxmax: 453,
      posxmin: 445,
      posymax: 513,
      posymin: 500,
    },
    {
      id: 29,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "25",
      sortId: null,
      partNumber: "1619P10963",
      partNumberFormatted: "1 619 P10 963",
      partName: "Housing Cover ",
      quantity: 1,
      price: 40.89,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "15",
      illustrationNumber: "1",
      posxmax: 277,
      posxmin: 258,
      posymax: 267,
      posymin: 254,
    },
    {
      id: 30,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "22",
      sortId: null,
      partNumber: "1619P10967",
      partNumberFormatted: "1 619 P10 967",
      partName: "Adjusting Slide ",
      quantity: 1,
      price: 12.02,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 728,
      posxmin: 709,
      posymax: 358,
      posymin: 344,
    },
    {
      id: 31,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "23",
      sortId: null,
      partNumber: "1619P10969",
      partNumberFormatted: "1 619 P10 969",
      partName: "Switch Button ",
      quantity: 1,
      price: 12.02,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 699,
      posxmin: 680,
      posymax: 455,
      posymin: 441,
    },
    {
      id: 32,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "29",
      sortId: null,
      partNumber: "1619P10970",
      partNumberFormatted: "1 619 P10 970",
      partName: "Air-Deflector Ring ",
      quantity: 1,
      price: 11.67,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 904,
      posxmin: 885,
      posymax: 637,
      posymin: 624,
    },
    {
      id: 33,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "18",
      sortId: null,
      partNumber: "1619P11487",
      partNumberFormatted: "1 619 P11 487",
      partName: "Compression Spring ",
      quantity: 1,
      price: 14.3,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 666,
      posxmin: 649,
      posymax: 323,
      posymin: 309,
    },
    {
      id: 34,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "810",
      sortId: null,
      partNumber: "1619P11715",
      partNumberFormatted: "1 619 P11 715",
      partName: "Carbon-Brush Set ",
      quantity: 1,
      price: 62.61,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "18",
      illustrationNumber: "1",
      posxmax: 533,
      posxmin: 506,
      posymax: 702,
      posymin: 688,
    },
    {
      id: 35,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "810",
      sortId: null,
      partNumber: "1619P11715",
      partNumberFormatted: "1 619 P11 715",
      partName: "Carbon-Brush Set ",
      quantity: 1,
      price: 62.61,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "18",
      illustrationNumber: "1",
      posxmax: 537,
      posxmin: 510,
      posymax: 267,
      posymin: 254,
    },
    {
      id: 36,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "831",
      sortId: null,
      partNumber: "1619P12186",
      partNumberFormatted: "1 619 P12 186",
      partName: "Gear Housing ",
      quantity: 1,
      price: 203.83,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "26",
      illustrationNumber: "1",
      posxmax: 856,
      posxmin: 831,
      posymax: 78,
      posymin: 64,
    },
    {
      id: 37,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "840",
      sortId: null,
      partNumber: "1619P12188",
      partNumberFormatted: "1 619 P12 188",
      partName: "Push Button ",
      quantity: 1,
      price: 26.56,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 907,
      posxmin: 880,
      posymax: 96,
      posymin: 83,
    },
    {
      id: 38,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "49",
      sortId: null,
      partNumber: "1619P12666",
      partNumberFormatted: "1 619 P12 666",
      partName: "Thread-forming tap. Screw ",
      quantity: 4,
      price: 14.3,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 1094,
      posxmin: 1076,
      posymax: 613,
      posymin: 600,
    },
    {
      id: 39,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "14",
      sortId: null,
      partNumber: "1619P13103",
      partNumberFormatted: "1 619 P13 103",
      partName: "groove ball bearing ",
      quantity: 1,
      price: 47.5,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "14",
      illustrationNumber: "1",
      posxmax: 805,
      posxmin: 787,
      posymax: 251,
      posymin: 237,
    },
    {
      id: 40,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "23",
      sortId: null,
      partNumber: "1619P13541",
      partNumberFormatted: "1 619 P13 541",
      partName: "Switch Button ",
      quantity: 1,
      price: 14.3,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 699,
      posxmin: 680,
      posymax: 455,
      posymin: 441,
    },
    {
      id: 41,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "30",
      sortId: null,
      partNumber: "1619P14139",
      partNumberFormatted: "1 619 P14 139",
      partName: "Air Distributor ",
      quantity: 1,
      price: 19.84,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "11",
      illustrationNumber: "1",
      posxmax: 729,
      posxmin: 710,
      posymax: 183,
      posymin: 169,
    },
    {
      id: 42,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "33",
      sortId: null,
      partNumber: "1619P14660",
      partNumberFormatted: "1 619 P14 660",
      partName: "groove ball bearing ",
      quantity: 1,
      price: 39.09,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "13",
      illustrationNumber: "1",
      posxmax: 953,
      posxmin: 934,
      posymax: 417,
      posymin: 404,
    },
    {
      id: 43,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "13",
      sortId: null,
      partNumber: "1619P14660",
      partNumberFormatted: "1 619 P14 660",
      partName: "groove ball bearing ",
      quantity: 1,
      price: 39.09,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "13",
      illustrationNumber: "1",
      posxmax: 504,
      posxmin: 486,
      posymax: 83,
      posymin: 69,
    },
    {
      id: 44,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "6",
      sortId: null,
      partNumber: "2600703012",
      partNumberFormatted: "2 600 703 012",
      partName: "Grommet Ã˜6,5-Ã˜6,9X95 MM",
      quantity: 1,
      price: 35.33,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "13",
      illustrationNumber: "1",
      posxmax: 429,
      posxmin: 419,
      posymax: 352,
      posymin: 338,
    },
    {
      id: 45,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "47",
      sortId: null,
      partNumber: "2609110052",
      partNumberFormatted: "2 609 110 052",
      partName: "Special Screw ",
      quantity: 1,
      price: 14.3,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 579,
      posxmin: 560,
      posymax: 356,
      posymin: 342,
    },
    {
      id: 46,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "858",
      sortId: null,
      partNumber: "2910641081",
      partNumberFormatted: "2 910 641 081",
      partName: "Oval-Head Screw DIN7985-M3,5X5-4.8-H",
      quantity: 2,
      price: 0,
      priceCurrencyISO: null,
      priceCurrencySymbol: null,
      priceGroup: null,
      illustrationNumber: "1",
      posxmax: 644,
      posxmin: 617,
      posymax: 378,
      posymin: 364,
    },
    {
      id: 47,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "45",
      sortId: null,
      partNumber: "2915011007",
      partNumberFormatted: "2 915 011 007",
      partName: "Hex Nut DIN 934-M6-8-A",
      quantity: 1,
      price: 14.3,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "10",
      illustrationNumber: "1",
      posxmax: 889,
      posxmin: 870,
      posymax: 299,
      posymin: 285,
    },
    {
      id: 48,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "28/3",
      sortId: null,
      partNumber: "2916660013",
      partNumberFormatted: "2 916 660 013",
      partName: "Retaining clip DIN 472-32X1,2 MM",
      quantity: 1,
      price: 21.72,
      priceCurrencyISO: "ZAR",
      priceCurrencySymbol: "R",
      priceGroup: "12",
      illustrationNumber: "1",
      posxmax: 965,
      posxmin: 934,
      posymax: 485,
      posymin: 472,
    },
  ],
  totalItems: 48,
  illustrationList: [
    {
      Page: 1,
      IllustrationType: "E",
      ImagePath: "https://quality.boschtoolservice.com/resource/public/images/3601C940.801.gif",
    },
    {
      Page: 2,
      IllustrationType: "E",
      ImagePath: "https://quality.boschtoolservice.com/resource/public/images/3601C940.802.gif",
    },
  ],
  currentIllustrationPage: 1,
  currentIllustrationType: "E",
  currentIllustrationPath:
    "https://quality.boschtoolservice.com/resource/public/images/3601C940.801.gif",
};
export const explosionDrawingData2 = {
  list: [
    {
      id: 49,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "651",
      sortId: null,
      partNumber: "1600A00XU5",
      partNumberFormatted: "1 600 A00 XU5",
      partName: "Protective Cover Ã˜100 MM",
      quantity: 1,
      price: 127,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 624,
      posxmin: 600,
      posymax: 467,
      posymin: 454,
    },
    {
      id: 50,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "650/1",
      sortId: null,
      partNumber: "160202509T",
      partNumberFormatted: "1 602 025 09T",
      partName: "Auxiliary Handle ",
      quantity: 1,
      price: 113,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 872,
      posxmin: 834,
      posymax: 175,
      posymin: 162,
    },
    {
      id: 51,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "895",
      sortId: null,
      partNumber: "1605430003",
      partNumberFormatted: "1 605 430 003",
      partName: "Grease Tube 225 ML",
      quantity: 1,
      price: 1633,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 445,
      posxmin: 419,
      posymax: 721,
      posymin: 707,
    },
    {
      id: 52,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "894",
      sortId: null,
      partNumber: "1615430020",
      partNumberFormatted: "1 615 430 020",
      partName: "Grease Tube 225 ML",
      quantity: 1,
      price: 1512,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 302,
      posxmin: 274,
      posymax: 721,
      posymin: 707,
    },
    {
      id: 53,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "28/1",
      sortId: null,
      partNumber: "1619P07440",
      partNumberFormatted: "1 619 P07 440",
      partName: "Ball Bearing ",
      quantity: 1,
      price: 219,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 963,
      posxmin: 934,
      posymax: 517,
      posymin: 504,
    },
    {
      id: 54,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "650/3",
      sortId: null,
      partNumber: "1619P08928",
      partNumberFormatted: "1 619 P08 928",
      partName: "Pin-Type Face-Wrench ",
      quantity: 1,
      price: 39,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 417,
      posxmin: 377,
      posymax: 619,
      posymin: 605,
    },
    {
      id: 55,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "650/3",
      sortId: null,
      partNumber: "1619P08928",
      partNumberFormatted: "1 619 P08 928",
      partName: "Pin-Type Face-Wrench ",
      quantity: 1,
      price: 39,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 586,
      posxmin: 546,
      posymax: 601,
      posymin: 587,
    },
    {
      id: 56,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "650/2",
      sortId: null,
      partNumber: "1619P09976",
      partNumberFormatted: "1 619 P09 976",
      partName: "Round Nut With 2 Holes ",
      quantity: 1,
      price: 54,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 692,
      posxmin: 652,
      posymax: 592,
      posymin: 579,
    },
    {
      id: 57,
      country: null,
      createBy: null,
      modifyBy: null,
      position: "650/5",
      sortId: null,
      partNumber: "1619P12159",
      partNumberFormatted: "1 619 P12 159",
      partName: "Clamping-Flange Ã˜22,3XÃ˜42 MM",
      quantity: 1,
      price: 51,
      priceCurrencyISO: "INR",
      priceCurrencySymbol: "Rs",
      priceGroup: "00",
      illustrationNumber: "2",
      posxmax: 633,
      posxmin: 593,
      posymax: 542,
      posymin: 529,
    },
  ],
  totalItems: 9,
  illustrationList: [
    {
      Page: 1,
      IllustrationType: "E",
      ImagePath: "https://quality.boschtoolservice.com/resource/public/images/3601C940.801.gif",
    },
    {
      Page: 2,
      IllustrationType: "E",
      ImagePath: "https://quality.boschtoolservice.com/resource/public/images/3601C940.802.gif",
    },
  ],
  currentIllustrationPage: 2,
  currentIllustrationType: "E",
  currentIllustrationPath:
    "https://quality.boschtoolservice.com/resource/public/images/3601C940.802.gif",
};
