export const PERMISSIONS = {
  ACCESS: {
    CAN_ACCESS_ASC_GLOBALLY: "AG_M",
    CAN_ACCESS_ASC_IN_REGION: "AR_M",
    CAN_ACCESS_ASC_IN_COUNTRY: "AC_M",
    CAN_ACCESS_ASC_IN_DISTRICT: "AD_M",
    CAN_ACCESS_GROUP_OF_SERVICE_CENTER: "ASGM",
    CAN_ACCESS_LINKED_SERVICE_CENTER: "ASLM",
  },

  APPROVAL: {
    CAN_VIEW: "A__V",
    CAN_APPROVE_WARRANTY_ITEMS: "A_WA",
    CAN_APPROVE_CHARGEABLE_ITEMS: "A_CA",
    CAN_APPROVE_SERVICE_GOODWILL_ITEMS: "A_SA",
    CAN_APPROVE_COMMERCIAL_GOODWILL_ITEMS: "A_GA",
    CAN_PERFORM_CLAIM_DECISION: "AC_A",
    CAN_REVERT_CLAIM_DECISION: "AC_R",
  },

  FEATURE_FLAGS: {
    CAN_VIEW: "FF_V",
    CAN_CREATE: "FF_C",
    CAN_TOGGLE: "FF_T",
    CAN_EDIT: "FF_E",
    CAN_DELETE: "FF_D",
  },

  DIAGNOSTICS: {
    CAN_VIEW_DIAGNOSTICS_ON_JOBS_AND_CLAIMS: "D__V",
    CAN_CREATE_DIAGNOSTICS: "D__C",
    CAN_EDIT_DIAGNOSTICS: "D__E",
    CAN_APPROVE_COST_ALLOCATION: "D_AA",
    CAN_VIEW_NET_DEALER_PRICE: "D_NV",

    CAN_VIEW_LABOUR_ITEMS: "DL_V",
    CAN_INSERT_AND_DELETE_LABOUR_ITEMS: "DL_I",
    CAN_EDIT_LABOUR_UNITS: "DLUE",
    CAN_EDIT_LABOUR_UNIT_PRICE: "DLPE",
    CAN_EDIT_DISCOUNT_ON_LABOUR: "DLDE",
    CAN_EDIT_TOTAL_ON_LABOUR: "DLTE",

    CAN_VIEW_FREIGHT_ITEMS: "DF_V",
    CAN_INSERT_AND_DELETE_FREIGHT_ITEMS: "DF_I",
    CAN_EDIT_FREIGHT_UNITS: "DFUE",
    CAN_EDIT_FREIGHT_UNIT_PRICE: "DFPE",
    CAN_EDIT_DISCOUNT_ON_FREIGHT: "DFDE",
    CAN_EDIT_TOTAL_ON_FREIGHT: "DFTE",

    CAN_VIEW_FULL_TOOLS_ITEMS: "DT_V",
    CAN_INSERT_AND_DELETE_FULL_TOOLS_ITEMS: "DT_I",
    CAN_EDIT_FULL_TOOLS_UNITS: "DTEU",
    CAN_EDIT_FULL_TOOLS_UNIT_PRICE: "DTEP",
    CAN_EDIT_DISCOUNT_ON_FULL_TOOLS: "DTDE",
    CAN_EDIT_TOTAL_ON_FULL_TOOLS: "DTTE",

    CAN_VIEW_SPARE_PARTS_ITEMS: "DS_V",
    CAN_INSERT_AND_DELETE_SPARE_PARTS_ITEMS: "DS_I",
    CAN_EDIT_SPARE_PARTS_UNITS: "DSUE",
    CAN_EDIT_SPARE_PARTS_UNIT_PRICE: "DSPE",
    CAN_EDIT_DISCOUNT_ON_SPARE_PARTS: "DSDE",
    CAN_EDIT_TOTAL_ON_SPARE_PARTS: "DSTE",

    CAN_EDIT_TOTAL_DISCOUNT: "D_TE",
    CAN_EDIT_TOTAL_AMOUNT: "D_AE",

    CAN_VIEW_PRICES: "DP_V",

    CAN_VIEW_WARRANTY_ITEMS: "D_WV",
    CAN_VIEW_SERVICE_OFFERING_ITEMS: "D_OV",
    CAN_VIEW_CHARGEABLE_ITEMS: "D_CV",
    CAN_VIEW_SPECIAL_CONTRACT_ITEMS: "D_SV",
    CAN_VIEW_COMMERCIAL_GOODWILL_ITEMS: "D_GV",

    CAN_VIEW_COST_ALLOCATION_ON_ITEM: "DA_V",
    CAN_ALLOCATE_WARRANTY_TO_ITEM: "D_WA",
    CAN_ALLOCATE_COMMERCIAL_GOODWILL_TO_ITEM: "D_GA",
    CAN_ALLOCATE_CHARGEABLE_TO_ITEM: "D_CA",
    CAN_ALLOCATE_SERVICE_GOODWILL_TO_ITEM: "D_SA",
    CAN_SEND_FOR_REVIEW: "D_RC",
  },

  INVENTORY_MANAGEMENT: {
    CAN_VIEW: "I__V",
    CAN_UPLOAD_AND_DOWNLOAD_ITEMS: "I__U",
    CAN_CREATE_EDIT_DELETE_LOCATION: "I_LE",
    CAN_CREATE_EDIT_DELETE_ITEM: "I_IE",
    CAN_REGISTER_ITEM_AT_LOCATION: "I_LR",
    CAN_UNREGISTER_ITEM_AT_LOCATION: "I_LU",
    CAN_ORDER_ITEM_FROM_EXTERNAL_SUPPLIER: "I_IO",
    CAN_CREATE_EDIT_DELETE_TECHNICIANS: "I_TE",
    CAN_SET_MIN_MAX_PER_IM_ITEM_STOCKING_LEVELS: "I_SM",
    CAN_STOP_ALL_TRANSACTIONS_FOR_STOCK_TAKING: "I_TS",
    CAN_MOVE_ITEMS_BETWEEN_RELATED_ASC: "I_IM",
  },

  CLAIM: {
    CAN_VIEW: "C__V",
    CAN_CREATE_WITHOUT_ORDER: "C__C",
    CAN_EDIT: "C__E",
    CAN_VIEW_TABLE: "CT_V",
    CAN_DELETE: "C__D",
    CAN_EDIT_APPROVED_CLAIM: "C_AE",
    CAN_REVERT_APPROVED_CLAIM: "C_AR",
  },

  CLIENT: {
    CAN_VIEW_LIST: "CL_V",
    CAN_UPLOAD_CLIENT_LIST: "CL_U",
    CAN_DOWNLOAD_CLIENT_LIST: "CL_D",
    CAN_EDIT_CLIENT_DETAILS: "CL_E",
    CAN_INSERT_CLIENT: "CL_I",
    CAN_ANONYMIZE_CLIENT: "CL_A",
  },

  COUNTRY_MANAGEMENT: {
    CAN_CREATE_EDIT_DELETE_SUSPEND_COUNTRY: "CM_E",
    CAN_CREATE_EDIT_DELETE_SUSPEND_REGION_OR_DISTRICT_IN_COUNTRY: "CMRE",
    CAN_CREATE_EDIT_DELETE_SUSPEND_BRAND_IN_COUNTRY: "CMBE",
  },

  ORDER: {
    CAN_VIEW: "O__V",
    CAN_CREATE: "O__C",
    CAN_EDIT: "O__E",
    CAN_VIEW_TABLE: "OT_V",
    CAN_ASSIGN_TECHNICIAN: "O_TA",
    CAN_ASSIGN_SELF: "O_TS",
    CAN_RECEIVE_JOB_ASSIGNMENT: "OA_R",
    CAN_DELETE: "O__D",
    CAN_EDIT_CLOSED_ORDER: "O_CE",
    CAN_REOPEN_CLOSED_ORDER: "O_CR",
    CAN_DOWNLOAD_ATTACHMENTS: "O_AD",
    CAN_UPDATE_JOB_STATUS: "O_SE",
    CAN_PUT_ON_HOLD_AND_RESUME: "O_HE",
  },

  PRICING: {
    CAN_VIEW: "P__V",
    CAN_UPLOAD_AND_DOWNLOAD_PRICING_FILE: "P__U",
    CAN_EDIT_DELETE_INSERT_PRICES_ON_PRICING_MODULE: "P__E",
  },

  REIMBURSEMENT: {
    CAN_VIEW: "R__V",
    CAN_CREATE: "R__C",
    CAN_EDIT: "R__E",
    CAN_VIEW_TABLE: "RT_V",
    CAN_DELETE_REIMBURSEMENT_REQUESTS: "R__D",
  },

  REPORT: {
    CAN_VIEW_NUMBER_OF_CLOSED_AND_DELIVERED_ORDERS_PER_TYPE: "RACV",
    CAN_VIEW_NUMBER_OF_OPEN_ORDERS: "RAOV",
    CAN_VIEW_NUMBER_OF_CLOSED_AND_DELIVERED_ORDERS: "RADV",
    CAN_VIEW_KPI_REPORT: "RAKV",
    CAN_VIEW_BASIC_REPORTS: "RBBV",
    CAN_CREATE_BIQIC: "RBBC",
    CAN_VIEW_ASA_DASHBOARD: "RBAV",
    CAN_VIEW_MONTHLY_DATA_REPORT: "RBMV",
  },

  SERVICE_CENTER: {
    CAN_VIEW: "SC_V",
    CAN_EDIT_ASC: "SC_E",
    CAN_CREATE_DELETE_ASC: "SC_C",
    CAN_SUSPEND_UNSUSPEND_ASC: "SC_S",
    CAN_EDIT_FREIGHT_PRICE_FOR_ASC: "SCFE",
    CAN_EDIT_LABOUR_PRICE_FOR_ASC: "SCLE",
    CAN_EDIT_NOTIFICATION_TYPES_FOR_ASC: "SCNE",
    CAN_MASS_UPLOAD_ASC_DATA_OR_USER_DATA: "SC_U",
  },

  SYSTEM_SETTINGS: {
    CAN_VIEW: "SS_V",
    CAN_UPLOAD_DOWNLOAD_TRANSLATIONS_AND_RELOAD_CACHE: "SSTU",
    CAN_UPLOAD_PRODUCT_DATA_FILES: "SSDU",
    CAN_SET_MAINTENANCE_MESSAGE: "SSMS",
    CAN_MANAGE_SPECIAL_MATERIALS: "SSSM",
  },

  USER_MANAGEMENT: {
    CAN_VIEW: "U__V",
    CAN_CREATE_USERS: "U__C",
    CAN_CREATE_EDIT_SUSPEND_TECHNICIANS: "U_TE",
    CAN_EDIT_USERS: "U__E",
    CAN_SUSPEND_USERS: "U__S",
    CAN_VIEW_TABLE: "UT_V",
  },

  REPORTS: {
    CAN_VIEW: "R__V",
  },
};
